### ISSUE TITLE
Deletar branch teste

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/sermil-core#185]
Cel @wagnerlopes 
Se o sr achar conveniente, talves fosse bom nós deletarmos esse branch teste. 
Nao foi uma boa ideia e nao funcionou como eu planejei. 
Causou mais confusao do que ajudou.
(Tb o branch teste do portal)

**Comment by wagnerlopes** [comment]
OK. Vamos organizar nosso trabalho.
Preciso resincronizar os branch no Github, desde a semana passada ficou
bagunçado e agora terá que ser feito uma reestruturação geral.
Vou baixar o que tem lá, acertar na minha maquina local com o que arrumei
durante o processo do agendamento, e depois subir para a Organização.


2016-07-21 12:47 GMT-03:00 Anselmo S Ribeiro <notifications@github.com>:
