### ISSUE TITLE
Refatorar Serviços

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/sermil-core#23]
Realocar as classes de serviços do portal e sermilweb para o sermil-core.

**Comment by 6975usa** [comment]
Corrigido
Cel Abreu, por favor, considerar a possibilidade de fazer o merge do branch next com essas alteracoes com o seu branch local.
Talves nao possa ser feito de forma automatica.
Aproveito para participar que nao to conseguindo clonar repositorios pelo git desktop (DGP?). Por esse motivo fazer merges locais vao ser muito dificeis para mim.
